### ISSUE TITLE
io.write over TLS/SSL

### ISSUE THREAD

**Issue by travispaul** [christiank/cadet#1]
I've encountered ad issue while trying to use Cadet, and I'm looking for some guidance on the best solution.

In order to use Lua scripting with bozohttpd over SSL, you must use `httpd.write()` and `httpd.print()` as those functions will use [bozohttpd's ssl functions](http://nxr.netbsd.org/xref/src/libexec/httpd/ssl-bozo.c#304) when appropriate, however you cannot `require 'httpd'` in cadet.lua, only in the initial script.

Would you be open to requiring httpd in cadet.lua and replacing the `io.write`with `httpd.write`? I believe Cadet will then work over SSL using `dofile()`. If so, I can make the change, do more testing and create a pull-request.

Do you know of another approach that could be used? Ultimately I think the scripting interface to Lua needs to be changed to remove the need for the httpd module, but that will require some more in-depth discussions.

Thanks for the feedback!

**Comment by ghost** [comment]
I believe httpd.write() and httpd.print() did not exist when I first wrote Cadet, so using those functions instead of my own is clearly the right thing to do.
